//! Build-time code generator for ZETS.
//!
//! Reads data files from `data/` at compile time, emits Rust `const` tables
//! into `$OUT_DIR/generated.rs`. Runtime code reads these via `include!`.
//!
//! Why: keep data in TSV files (git-friendly, editable, greppable) without
//! runtime parsing overhead. Single binary output, zero runtime I/O for
//! core tables.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let data_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("data");

    // Re-run build if any data file changes
    println!("cargo:rerun-if-changed=data");
    rerun_dir(&data_dir);

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs — do not edit.\n\n");

    generate_relations(&data_dir.join("core/relations.tsv"), &mut out);
    generate_languages(&data_dir.join("core/languages.tsv"), &mut out);
    generate_system_synsets(&data_dir.join("core/system_synsets.tsv"), &mut out);
    generate_hebrew_prefixes(&data_dir.join("hebrew/prefixes.tsv"), &mut out);
    generate_hebrew_suffixes(&data_dir.join("hebrew/suffixes.tsv"), &mut out);
    generate_test_vectors(&data_dir.join("test_vectors/unp_v1.tsv"), &mut out);

    fs::write(out_dir.join("generated.rs"), out).expect("write generated.rs");
}

fn rerun_dir(dir: &Path) {
    if let Ok(entries) = fs::read_dir(dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.is_dir() {
                rerun_dir(&p);
            } else {
                println!("cargo:rerun-if-changed={}", p.display());
            }
        }
    }
}

/// Read TSV, skip comment lines (#) and blank lines.
fn read_tsv_rows(path: &Path) -> Vec<Vec<String>> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {}", path.display(), e));
    text.lines()
        .map(str::trim_end)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|l| l.split('\t').map(str::to_string).collect())
        .collect()
}

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn generate_relations(path: &Path, out: &mut String) {
    let rows = read_tsv_rows(path);
    out.push_str("// --- Relations ---\n");
    out.push_str(&format!("pub const RELATION_COUNT: usize = {};\n", rows.len()));
    out.push_str("pub const RELATION_NAMES: &[&str] = &[\n");
    let mut by_id: Vec<(usize, String)> = rows.iter().map(|r| {
        (r[0].parse::<usize>().unwrap(), r[1].clone())
    }).collect();
    by_id.sort_by_key(|(i, _)| *i);
    for (_, name) in &by_id {
        out.push_str(&format!("    \"{}\",\n", escape_rust_str(name)));
    }
    out.push_str("];\n\n");

    out.push_str("pub const RELATION_INVERSES: &[u8] = &[\n");
    for r in &rows {
        out.push_str(&format!("    {}, // {} <-> {}\n",
            r[2], r[1], if r[2] == "255" { "(none)" } else { &r[1] }));
    }
    out.push_str("];\n\n");
}

fn generate_languages(path: &Path, out: &mut String) {
    let rows = read_tsv_rows(path);
    out.push_str("// --- Languages (ISO 639-1) ---\n");
    out.push_str("pub struct LanguageMeta {\n");
    out.push_str("    pub code: &'static str,\n");
    out.push_str("    pub name_native: &'static str,\n");
    out.push_str("    pub name_english: &'static str,\n");
    out.push_str("    pub script: &'static str,\n");
    out.push_str("    pub rtl: bool,\n");
    out.push_str("    pub default_active: bool,\n");
    out.push_str("}\n\n");
    out.push_str(&format!("pub const LANGUAGE_COUNT: usize = {};\n", rows.len()));
    out.push_str("pub const LANGUAGES: &[LanguageMeta] = &[\n");
    for r in &rows {
        out.push_str(&format!(
            "    LanguageMeta {{ code: \"{}\", name_native: \"{}\", name_english: \"{}\", script: \"{}\", rtl: {}, default_active: {} }},\n",
            escape_rust_str(&r[0]),
            escape_rust_str(&r[1]),
            escape_rust_str(&r[2]),
            escape_rust_str(&r[3]),
            r[4] == "1",
            r[5] == "1",
        ));
    }
    out.push_str("];\n\n");
}

fn generate_system_synsets(path: &Path, out: &mut String) {
    let rows = read_tsv_rows(path);
    out.push_str("// --- System synsets (meta-graph reserved IDs 0..999) ---\n");
    out.push_str("pub struct SystemSynset {\n");
    out.push_str("    pub id: u32,\n");
    out.push_str("    pub key: &'static str,\n");
    out.push_str("    pub category: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str(&format!("pub const SYSTEM_SYNSET_COUNT: usize = {};\n", rows.len()));
    out.push_str("pub const SYSTEM_SYNSETS: &[SystemSynset] = &[\n");
    for r in &rows {
        out.push_str(&format!(
            "    SystemSynset {{ id: {}, key: \"{}\", category: \"{}\" }},\n",
            r[0], escape_rust_str(&r[1]), escape_rust_str(&r[2]),
        ));
    }
    out.push_str("];\n\n");
}

fn generate_hebrew_prefixes(path: &Path, out: &mut String) {
    let rows = read_tsv_rows(path);
    out.push_str("// --- Hebrew prefixes (longest-first) ---\n");
    // Sort by char length descending (longest first)
    let mut sorted: Vec<&Vec<String>> = rows.iter().collect();
    sorted.sort_by(|a, b| {
        let la: usize = a[1].parse().unwrap();
        let lb: usize = b[1].parse().unwrap();
        lb.cmp(&la)
    });
    out.push_str(&format!("pub const HEBREW_PREFIX_COUNT: usize = {};\n", sorted.len()));
    out.push_str("pub const HEBREW_PREFIXES: &[&str] = &[\n");
    for r in &sorted {
        out.push_str(&format!("    \"{}\", // {} ({})\n",
            escape_rust_str(&r[0]), r[2], r[3]));
    }
    out.push_str("];\n\n");
}

fn generate_hebrew_suffixes(path: &Path, out: &mut String) {
    let rows = read_tsv_rows(path);
    out.push_str("// --- Hebrew suffixes (post-normalized form, longest-first) ---\n");
    let mut sorted: Vec<&Vec<String>> = rows.iter().collect();
    sorted.sort_by(|a, b| {
        let la: usize = a[1].parse().unwrap();
        let lb: usize = b[1].parse().unwrap();
        lb.cmp(&la)
    });
    out.push_str(&format!("pub const HEBREW_SUFFIX_COUNT: usize = {};\n", sorted.len()));
    out.push_str("pub const HEBREW_SUFFIXES: &[&str] = &[\n");
    for r in &sorted {
        out.push_str(&format!("    \"{}\", // {} ({})\n",
            escape_rust_str(&r[0]), r[2], r[3]));
    }
    out.push_str("];\n\n");
}

fn generate_test_vectors(path: &Path, out: &mut String) {
    let rows = read_tsv_rows(path);
    out.push_str("// --- UNP test vectors ---\n");
    out.push_str("pub struct TestVector {\n");
    out.push_str("    pub lang: &'static str,\n");
    out.push_str("    pub input: &'static str,\n");
    out.push_str("    pub expected: &'static str,\n");
    out.push_str("    pub category: &'static str,\n");
    out.push_str("    pub note: &'static str,\n");
    out.push_str("}\n\n");
    out.push_str(&format!("pub const TEST_VECTOR_COUNT: usize = {};\n", rows.len()));
    out.push_str("pub const TEST_VECTORS: &[TestVector] = &[\n");
    for r in &rows {
        out.push_str(&format!(
            "    TestVector {{ lang: \"{}\", input: \"{}\", expected: \"{}\", category: \"{}\", note: \"{}\" }},\n",
            escape_rust_str(&r[0]),
            escape_rust_str(&r[1]),
            escape_rust_str(&r[2]),
            escape_rust_str(&r[3]),
            escape_rust_str(&r.get(4).cloned().unwrap_or_default()),
        ));
    }
    out.push_str("];\n\n");
}
