//! ZETS library — Deterministic knowledge graph engine for edge devices.
//!
//! # Architecture
//!
//! Single binary. Zero runtime dependencies. Data stored as TSV in `data/`,
//! baked at compile time via `build.rs` into `$OUT_DIR/generated.rs`.
//!
//! The system describes itself in its own graph: reserved synset IDs 0..999
//! hold system concepts (languages, relations, permissions). IDs 10000+ hold
//! user-facing content. This is the "homoiconic 11th sphere" — meta-rules
//! live in the graph like any other node.
//!
//! # Current coverage (Week 1-2)
//!
//! - `LangCode`: ISO 639-1 language identifier (2 bytes, Copy)
//! - `unp`: Unified Normalization Pipeline (NFC stub, trim, collapse, lang-specific, lemmatize)
//! - `hebrew`: niqud detection, final-form normalization, rules-based stemmer
//! - `meta_graph`: system synsets pre-seeded at EdgeStore creation
//! - `edge_store`: SOA columnar graph, 10 bytes/edge, binary serialization
//! - `bloom`: custom Bloom filter, FNV-1a + Kirsch-Mitzenmacher
//!
//! # Data loading strategy
//!
//! - **Core tables** (prefixes, suffixes, relations, system synsets): embedded
//!   at compile time. Always present, zero runtime I/O.
//! - **Language packs** (surface→lemma dictionaries, wikipedia content):
//!   downloaded on demand when user activates a language. Stored at
//!   `~/.zets/packs/{code}_v{n}.pack`.

#![forbid(unsafe_code)]
#![warn(clippy::all, clippy::pedantic)]
#![allow(clippy::must_use_candidate, clippy::missing_errors_doc)]
#![allow(clippy::module_name_repetitions, clippy::missing_panics_doc)]

use std::fmt;



// Compile-time data tables generated by `build.rs` from `data/*.tsv`.
include!(concat!(env!("OUT_DIR"), "/generated.rs"));

// ============================================================================
// CORE TYPES
// ============================================================================

/// Language identifier — ISO 639-1 2-letter lowercase code.
///
/// Stored as 2 bytes, always `Copy`. Comparable in a single `cmp` instruction.
///
/// # Examples
///
/// ```ignore
/// let he = LangCode::HEBREW;
/// let parsed = LangCode::parse("HE").unwrap();  // case-insensitive
/// assert_eq!(he, parsed);
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LangCode([u8; 2]);

impl LangCode {
    pub const HEBREW: LangCode = LangCode(*b"he");
    pub const ENGLISH: LangCode = LangCode(*b"en");
    pub const ARABIC: LangCode = LangCode(*b"ar");
    pub const CHINESE: LangCode = LangCode(*b"cn");
    pub const RUSSIAN: LangCode = LangCode(*b"ru");
    pub const JAPANESE: LangCode = LangCode(*b"ja");
    pub const SPANISH: LangCode = LangCode(*b"es");
    pub const FRENCH: LangCode = LangCode(*b"fr");
    pub const GERMAN: LangCode = LangCode(*b"de");
    pub const PORTUGUESE: LangCode = LangCode(*b"pt");

    /// Parse a 2-letter ASCII code, case-insensitive. Returns `None` if
    /// the input is not exactly 2 ASCII alphabetic characters.
    #[inline]
    pub const fn parse(s: &str) -> Option<Self> {
        let b = s.as_bytes();
        if b.len() != 2 {
            return None;
        }
        let b0 = b[0].to_ascii_lowercase();
        let b1 = b[1].to_ascii_lowercase();
        if !b0.is_ascii_lowercase() || !b1.is_ascii_lowercase() {
            return None;
        }
        Some(Self([b0, b1]))
    }

    /// Internal representation as two bytes.
    #[inline]
    pub const fn as_bytes(self) -> [u8; 2] {
        self.0
    }

    /// As a string slice.
    #[inline]
    pub fn as_str(&self) -> &str {
        // Constructors guarantee valid ASCII, so UTF-8 validity is trivial.
        std::str::from_utf8(&self.0).unwrap_or("??")
    }

    /// Look up the language metadata from the compile-time table.
    /// Returns `None` if the code is not in the supported list.
    pub fn meta(self) -> Option<&'static LanguageMeta> {
        LANGUAGES.iter().find(|m| m.code.as_bytes() == self.0)
    }

    /// True if the language is right-to-left. Returns false for unknown codes.
    pub fn is_rtl(self) -> bool {
        self.meta().is_some_and(|m| m.rtl)
    }
}

impl fmt::Debug for LangCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "LangCode({})", self.as_str())
    }
}

impl fmt::Display for LangCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// A canonical form of text. Opaque wrapper that prevents mixing raw and
/// normalized text at the type level. Constructed only via [`unp::normalize`].
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Canonical {
    bytes: Vec<u8>,
    lang: LangCode,
}

impl Canonical {
    /// Private — only UNP can construct these.
    fn new(s: String, lang: LangCode) -> Self {
        Self { bytes: s.into_bytes(), lang }
    }

    #[inline]
    pub fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Safe because UNP only produces valid UTF-8.
    #[inline]
    pub fn as_str(&self) -> &str {
        std::str::from_utf8(&self.bytes).expect("Canonical is always valid UTF-8")
    }

    #[inline]
    pub const fn language(&self) -> LangCode {
        self.lang
    }

    #[inline]
    pub fn len(&self) -> usize {
        self.bytes.len()
    }

    #[inline]
    pub fn is_empty(&self) -> bool {
        self.bytes.is_empty()
    }
}

/// What kind of content are we identifying? Determines the identity scheme.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContentKind {
    Word,
    Phrase,
    Sentence,
    Document,
}

/// Synset identifier. Stored as u24 on disk (3 bytes), u32 in memory.
///
/// Reserved ranges:
/// - `0..1000` — system/meta synsets (languages, relations, permissions)
/// - `1000..10000` — reserved for future system use
/// - `10000..` — user-facing content
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SynsetId(pub u32);

impl SynsetId {
    pub const SYSTEM_ROOT: SynsetId = SynsetId(0);
    pub const LANGUAGE_REGISTRY: SynsetId = SynsetId(1);
    pub const RELATION_REGISTRY: SynsetId = SynsetId(2);
    pub const PERMISSION_REGISTRY: SynsetId = SynsetId(3);
    pub const STATUS_REGISTRY: SynsetId = SynsetId(4);
    pub const USER_REGISTRY: SynsetId = SynsetId(5);

    /// First synset ID available for user content.
    pub const USER_CONTENT_START: u32 = 10_000;

    /// Maximum representable value (24-bit).
    pub const MAX: u32 = 0x00FF_FFFF;

    #[inline]
    pub const fn is_system(self) -> bool {
        self.0 < 1000
    }

    #[inline]
    pub const fn is_user(self) -> bool {
        self.0 >= Self::USER_CONTENT_START
    }
}

/// The identity of a piece of content in the ZETS graph.
#[derive(Debug, Clone)]
pub enum Identity {
    Word(Canonical),
    Phrase(Vec<SynsetId>),
    Hash128([u8; 16]),
    Hash256([u8; 32]),
}

// ============================================================================
// HEBREW — character classification, niqud, stemmer
// ============================================================================

pub mod hebrew {
    //! Hebrew-specific text processing.

    /// Is this character niqud (vowel point) or cantillation mark?
    ///
    /// Ranges: U+0591..U+05AF (cantillation), U+05B0..U+05BD (points),
    /// U+05BF (rafe), U+05C1..U+05C2 (sin/shin dots),
    /// U+05C4..U+05C5 (meteg/hiriq marks), U+05C7 (holam haser).
    #[inline]
    #[must_use]
    pub const fn is_niqud(c: char) -> bool {
        let code = c as u32;
        matches!(code, 0x0591..=0x05AF | 0x05B0..=0x05BD | 0x05BF
            | 0x05C1..=0x05C2 | 0x05C4..=0x05C5 | 0x05C7)
    }

    /// Geresh (U+05F3) and gershayim (U+05F4).
    #[inline]
    #[must_use]
    pub const fn is_hebrew_punctuation(c: char) -> bool {
        matches!(c as u32, 0x05F3 | 0x05F4)
    }

    /// Is this a Hebrew letter (including final forms)?
    #[inline]
    #[must_use]
    pub const fn is_hebrew_letter(c: char) -> bool {
        matches!(c as u32, 0x05D0..=0x05EA)
    }

    /// Convert final-form letter to regular form.
    /// ך→כ, ם→מ, ן→נ, ף→פ, ץ→צ. Everything else unchanged.
    #[inline]
    #[must_use]
    pub const fn normalize_final_form(c: char) -> char {
        match c {
            'ך' => 'כ',
            'ם' => 'מ',
            'ן' => 'נ',
            'ף' => 'פ',
            'ץ' => 'צ',
            _ => c,
        }
    }

    /// Minimum root length to preserve during stemming.
    pub const MIN_ROOT_CHARS: usize = 3;

    /// Strip niqud and cantillation marks.
    #[must_use]
    pub fn strip_niqud(s: &str) -> String {
        s.chars().filter(|&c| !is_niqud(c)).collect()
    }

    /// Safe Hebrew canonicalization — only normalize final forms.
    ///
    /// Does NOT strip prefixes or suffixes; that requires a dictionary
    /// (Week 3+) because naive stripping over-strips common words.
    #[must_use]
    pub fn canonicalize(word: &str) -> String {
        let word = word.trim();
        if word.is_empty() {
            return String::new();
        }
        // Only process purely-Hebrew words; pass others through.
        if !word.chars().all(|c| is_hebrew_letter(c) || is_hebrew_punctuation(c)) {
            return word.to_string();
        }
        word.chars().map(normalize_final_form).collect()
    }

    /// Aggressive rules-based stemmer — Week 3+ fallback only.
    ///
    /// Uses prefix/suffix tables from `build.rs`. Strips one longest-matching
    /// prefix and one longest-matching suffix, preserving minimum root length.
    ///
    /// Use only when dictionary lookup misses. Will over-strip common words
    /// whose first letter happens to be a prefix letter.
    #[must_use]
    pub fn aggressive_stem_fallback(word: &str) -> String {
        let word = word.trim();
        if word.is_empty() {
            return String::new();
        }
        if !word.chars().all(|c| is_hebrew_letter(c) || is_hebrew_punctuation(c)) {
            return word.to_string();
        }

        let mut stem: String = word.chars().map(normalize_final_form).collect();

        for prefix in super::HEBREW_PREFIXES {
            let p_chars = prefix.chars().count();
            let s_chars = stem.chars().count();
            if s_chars >= p_chars + MIN_ROOT_CHARS && stem.starts_with(prefix) {
                stem = stem[prefix.len()..].to_string();
                break;
            }
        }

        for suffix in super::HEBREW_SUFFIXES {
            let sf_chars = suffix.chars().count();
            let s_chars = stem.chars().count();
            if s_chars >= sf_chars + MIN_ROOT_CHARS && stem.ends_with(suffix) {
                stem.truncate(stem.len() - suffix.len());
                break;
            }
        }

        stem
    }
}

// ============================================================================
// UNP — Unified Normalization Pipeline
// ============================================================================

pub mod unp {
    //! Single source of truth for text normalization. All device instances
    //! MUST produce bit-identical canonical output for identical input.

    use super::{hebrew, Canonical, ContentKind, Identity, LangCode, SynsetId};

    /// Normalize raw text to canonical form.
    #[must_use]
    pub fn normalize(raw: &str, lang: LangCode) -> Canonical {
        let step1 = nfc(raw);
        let step2 = step1.trim().to_string();
        let step3 = collapse_whitespace(&step2);
        let step4 = strip_language_specific(&step3, lang);
        let step5 = lemmatize(&step4, lang);
        Canonical::new(step5, lang)
    }

    /// Identify content with its type-appropriate identity scheme.
    #[must_use]
    pub fn identify(raw: &str, lang: LangCode, kind: ContentKind) -> Identity {
        let canon = normalize(raw, lang);
        match kind {
            ContentKind::Word => Identity::Word(canon),
            ContentKind::Phrase => Identity::Phrase(tokenize_phrase(&canon)),
            ContentKind::Sentence => Identity::Hash128(fnv_128_with_lang(canon.as_bytes(), lang)),
            ContentKind::Document => Identity::Hash256(fnv_256_with_lang(canon.as_bytes(), lang)),
        }
    }

    /// Unicode NFC normalization.
    ///
    /// Week 1-2: pass-through. Modern corpora are typically already NFC.
    /// Week 3+: hand-rolled lookup table for our character ranges (~20KB).
    #[inline]
    fn nfc(s: &str) -> String {
        s.to_string()
    }

    /// Collapse all whitespace runs to single ASCII spaces.
    fn collapse_whitespace(s: &str) -> String {
        let mut out = String::with_capacity(s.len());
        let mut last_was_space = false;
        for c in s.chars() {
            if c.is_whitespace() {
                if !last_was_space {
                    out.push(' ');
                    last_was_space = true;
                }
            } else {
                out.push(c);
                last_was_space = false;
            }
        }
        out
    }

    fn strip_language_specific(s: &str, lang: LangCode) -> String {
        if lang == LangCode::HEBREW {
            hebrew::strip_niqud(s)
        } else if lang == LangCode::ARABIC {
            strip_tatweel(s)
        } else if lang == LangCode::ENGLISH {
            s.to_lowercase()
        } else {
            // Unknown or unhandled language — no language-specific changes.
            s.to_string()
        }
    }

    fn strip_tatweel(s: &str) -> String {
        s.chars().filter(|&c| c != '\u{0640}').collect()
    }

    fn lemmatize(s: &str, lang: LangCode) -> String {
        if lang == LangCode::HEBREW {
            // Week 1-2: canonicalization only. Week 3+ adds dictionary lookup,
            // with `aggressive_stem_fallback` as tail-case.
            hebrew::canonicalize(s)
        } else {
            s.to_string()
        }
    }

    /// Placeholder: tokenize a phrase into synset IDs via dictionary lookup.
    /// Week 3+ implementation; currently returns empty.
    #[inline]
    fn tokenize_phrase(_canon: &Canonical) -> Vec<SynsetId> {
        Vec::new()
    }

    // --- Hash placeholders (FNV-1a, not cryptographic) ---
    //
    // Week 3 replaces with BLAKE3 (via crate; security-critical).
    //
    // IMPORTANT: `_with_lang` variants mix the 2-byte language code into the
    // hash seed. This guarantees that homographs across languages produce
    // DIFFERENT hashes. Example: "gift"[EN] (present) vs "gift"[DE] (poison) —
    // same bytes, different meaning, must have different synset/hash.

    const FNV_OFFSET_128: u128 = 0x6c62_272e_07bb_0142_62b8_2175_6295_c58d;
    const FNV_PRIME_128: u128 = 0x0000_0000_0100_0000_0000_0000_0000_013b;

    /// FNV-1a 128-bit with language code mixed into the seed.
    ///
    /// Layout of input: `[lang_byte_0, lang_byte_1, 0x1F, data...]`
    /// The `0x1F` separator (ASCII unit-separator) prevents collisions between
    /// `("en", "gift")` and `("e", "ngift")`.
    #[inline]
    fn fnv_128_with_lang(data: &[u8], lang: super::LangCode) -> [u8; 16] {
        let lang_bytes = lang.as_bytes();
        let mut h = FNV_OFFSET_128;
        h ^= u128::from(lang_bytes[0]);
        h = h.wrapping_mul(FNV_PRIME_128);
        h ^= u128::from(lang_bytes[1]);
        h = h.wrapping_mul(FNV_PRIME_128);
        h ^= u128::from(0x1Fu8); // unit separator
        h = h.wrapping_mul(FNV_PRIME_128);
        for &b in data {
            h ^= u128::from(b);
            h = h.wrapping_mul(FNV_PRIME_128);
        }
        h.to_le_bytes()
    }

    /// FNV-1a 256-bit with language code mixed in.
    #[inline]
    fn fnv_256_with_lang(data: &[u8], lang: super::LangCode) -> [u8; 32] {
        let lo = fnv_128_with_lang(data, lang);
        let mut sep = data.to_vec();
        sep.push(0xAA);
        let hi = fnv_128_with_lang(&sep, lang);
        let mut out = [0u8; 32];
        out[..16].copy_from_slice(&lo);
        out[16..].copy_from_slice(&hi);
        out
    }
}

// ============================================================================
// META-GRAPH — system describes itself
// ============================================================================

pub mod meta_graph {
    //! The 11th sphere: system rules live in the graph.
    //!
    //! System synsets are pre-seeded in the reserved ID range 0..999.
    //! User content starts at SynsetId::USER_CONTENT_START (10_000).
    //!
    //! This gives free introspection: querying `outgoing(LANGUAGE_REGISTRY)`
    //! returns all languages as regular graph edges.

    use super::{SynsetId, SystemSynset, SYSTEM_SYNSETS, LANGUAGES};

    /// Look up a system synset by its canonical key.
    /// Example: `by_key("he")` returns the synset for Hebrew.
    pub fn by_key(key: &str) -> Option<SynsetId> {
        SYSTEM_SYNSETS
            .iter()
            .find(|s| s.key == key)
            .map(|s| SynsetId(s.id))
    }

    /// Look up a system synset by category.
    pub fn by_category(category: &str) -> Vec<SynsetId> {
        SYSTEM_SYNSETS
            .iter()
            .filter(|s| s.category == category)
            .map(|s| SynsetId(s.id))
            .collect()
    }

    /// List the system synsets that belong to a category.
    pub fn category_entries(category: &str) -> Vec<&'static SystemSynset> {
        SYSTEM_SYNSETS
            .iter()
            .filter(|s| s.category == category)
            .collect()
    }

    /// All language codes that have a corresponding system synset.
    pub fn known_language_codes() -> Vec<&'static str> {
        LANGUAGES.iter().map(|l| l.code).collect()
    }
}

// ============================================================================
// EDGE STORE — Struct of Arrays graph storage
// ============================================================================

pub mod edge_store {
    //! Columnar edge storage.
    //!
    //! Layout (10 bytes per edge):
    //! - `sources`:    3 bytes (u24)
    //! - `targets`:    3 bytes (u24)
    //! - `rel_weight`: 1 byte (5 bits relation + 3 bits weight)
    //! - `provenance`: 3 bytes (u24)
    //!
    //! SOA beats AOS because graph walks touch mostly source/target, so
    //! cache line utilization is ~2.3× higher.

    use super::{SynsetId, SYSTEM_SYNSETS};
    use std::io::{self, Read, Write};
    

    /// 27 relation types (fits in 5 bits, MAX=26).
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    pub enum Relation {
        IsA = 0,
        HasPart = 1,
        MemberOf = 2,
        SameAs = 3,
        NearSynonym = 4,
        Causes = 5,
        Enables = 6,
        Prevents = 7,
        Precedes = 8,
        Follows = 9,
        UsedFor = 10,
        Requires = 11,
        Produces = 12,
        Satisfies = 13,
        Implies = 14,
        Contradicts = 15,
        DefinedBy = 16,
        ExampleOf = 17,
        LocatedIn = 18,
        Contains = 19,
        AdjacentTo = 20,
        AgentOf = 21,
        PatientOf = 22,
        InstrumentOf = 23,
        DerivedFrom = 24,
        VariationOf = 25,
        OpposedTo = 26,
        TextNext = 27,
        AppearsIn = 28,
        Cites = 29,
    }

    impl Relation {
        pub const MAX_VALUE: u8 = 29;

        #[inline]
        pub const fn from_u8(v: u8) -> Option<Self> {
            match v {
                0 => Some(Self::IsA), 1 => Some(Self::HasPart),
                2 => Some(Self::MemberOf), 3 => Some(Self::SameAs),
                4 => Some(Self::NearSynonym), 5 => Some(Self::Causes),
                6 => Some(Self::Enables), 7 => Some(Self::Prevents),
                8 => Some(Self::Precedes), 9 => Some(Self::Follows),
                10 => Some(Self::UsedFor), 11 => Some(Self::Requires),
                12 => Some(Self::Produces), 13 => Some(Self::Satisfies),
                14 => Some(Self::Implies), 15 => Some(Self::Contradicts),
                16 => Some(Self::DefinedBy), 17 => Some(Self::ExampleOf),
                18 => Some(Self::LocatedIn), 19 => Some(Self::Contains),
                20 => Some(Self::AdjacentTo), 21 => Some(Self::AgentOf),
                22 => Some(Self::PatientOf), 23 => Some(Self::InstrumentOf),
                24 => Some(Self::DerivedFrom), 25 => Some(Self::VariationOf),
                26 => Some(Self::OpposedTo),
                27 => Some(Self::TextNext),
                28 => Some(Self::AppearsIn),
                29 => Some(Self::Cites),
                _ => None,
            }
        }

        /// Human-readable name, from the compile-time table.
        #[inline]
        pub fn name(self) -> &'static str {
            super::RELATION_NAMES[self as usize]
        }

        /// Inverse relation if defined, else None.
        #[inline]
        pub fn inverse(self) -> Option<Self> {
            let inv = super::RELATION_INVERSES[self as usize];
            if inv == 255 { None } else { Self::from_u8(inv) }
        }

        /// The system synset representing this relation itself (homoiconic).
        /// Example: `Relation::IsA.as_synset()` returns SynsetId(30).
        #[inline]
        pub const fn as_synset(self) -> SynsetId {
            SynsetId(30 + self as u32)
        }
    }

    /// A complete edge in user-facing form.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Edge {
        pub source: SynsetId,
        pub target: SynsetId,
        pub relation: Relation,
        pub weight: u8,        // 0..=7 (3 bits)
        pub provenance: u32,   // u24 index into ProvenanceTable
    }

    #[inline]
    const fn pack_rel_weight(rel: Relation, weight: u8) -> u8 {
        // weight in top 3 bits, relation in bottom 5 bits
        (rel as u8) | (weight << 5)
    }

    #[inline]
    const fn unpack_rel_weight(byte: u8) -> (Relation, u8) {
        let rel_bits = byte & 0b0001_1111;
        let weight = byte >> 5;
        let rel = match Relation::from_u8(rel_bits) {
            Some(r) => r,
            None => Relation::IsA, // fallback for corrupt data
        };
        (rel, weight)
    }

    #[inline]
    fn write_u24(buf: &mut Vec<u8>, value: u32) {
        debug_assert!(value <= SynsetId::MAX, "u24 overflow: {value}");
        buf.push((value & 0xFF) as u8);
        buf.push(((value >> 8) & 0xFF) as u8);
        buf.push(((value >> 16) & 0xFF) as u8);
    }

    #[inline]
    const fn read_u24(buf: &[u8], i: usize) -> u32 {
        let off = i * 3;
        (buf[off] as u32) | ((buf[off + 1] as u32) << 8) | ((buf[off + 2] as u32) << 16)
    }

    /// In-memory columnar edge store.
    #[derive(Debug, Default, Clone)]
    pub struct EdgeStore {
        sources: Vec<u8>,
        targets: Vec<u8>,
        rel_weight: Vec<u8>,
        provenance: Vec<u8>,
    }

    impl EdgeStore {
        const MAGIC: &'static [u8] = b"ZEDG";
        const VERSION: u8 = 1;

        #[inline]
        #[must_use]
        pub fn new() -> Self {
            Self::default()
        }

        /// Create with pre-allocated capacity for `n` edges.
        #[must_use]
        pub fn with_capacity(n: usize) -> Self {
            Self {
                sources: Vec::with_capacity(n * 3),
                targets: Vec::with_capacity(n * 3),
                rel_weight: Vec::with_capacity(n),
                provenance: Vec::with_capacity(n * 3),
            }
        }

        /// Create with meta-graph pre-seeded: system synsets linked into their
        /// registry nodes. The graph describes itself from step zero.
        #[must_use]
        pub fn new_with_meta() -> Self {
            let mut store = Self::with_capacity(SYSTEM_SYNSETS.len());

            // Link each system synset to its category parent via MEMBER_OF.
            for synset in SYSTEM_SYNSETS {
                let parent_id = match synset.category {
                    "language" => SynsetId::LANGUAGE_REGISTRY,
                    "relation" => SynsetId::RELATION_REGISTRY,
                    "permission" => SynsetId::PERMISSION_REGISTRY,
                    "status" => SynsetId::STATUS_REGISTRY,
                    "system" => SynsetId::SYSTEM_ROOT,
                    _ => continue,
                };
                if synset.id == parent_id.0 {
                    continue; // don't self-link registries
                }
                store.push(Edge {
                    source: SynsetId(synset.id),
                    target: parent_id,
                    relation: Relation::MemberOf,
                    weight: 7, // maximum confidence for system facts
                    provenance: 0, // provenance slot 0 = "system bootstrap"
                });
            }
            store
        }

        #[inline]
        pub fn len(&self) -> usize {
            self.rel_weight.len()
        }

        #[inline]
        pub fn is_empty(&self) -> bool {
            self.rel_weight.is_empty()
        }

        /// Bytes used by the store (excluding Vec overhead).
        #[inline]
        pub fn bytes_used(&self) -> usize {
            self.sources.len() + self.targets.len()
                + self.rel_weight.len() + self.provenance.len()
        }

        /// Append an edge. Returns its index.
        pub fn push(&mut self, edge: Edge) -> usize {
            let idx = self.len();
            write_u24(&mut self.sources, edge.source.0);
            write_u24(&mut self.targets, edge.target.0);
            self.rel_weight.push(pack_rel_weight(edge.relation, edge.weight));
            write_u24(&mut self.provenance, edge.provenance);
            idx
        }

        /// Read edge at index. `None` if out of bounds.
        #[inline]
        pub fn get(&self, i: usize) -> Option<Edge> {
            if i >= self.len() {
                return None;
            }
            let source = SynsetId(read_u24(&self.sources, i));
            let target = SynsetId(read_u24(&self.targets, i));
            let (relation, weight) = unpack_rel_weight(self.rel_weight[i]);
            let provenance = read_u24(&self.provenance, i);
            Some(Edge { source, target, relation, weight, provenance })
        }

        pub fn iter(&self) -> EdgeIter<'_> {
            EdgeIter { store: self, pos: 0 }
        }

        /// Edges where `source == src`. Linear scan; Week 3 adds bitmap index.
        pub fn outgoing(&self, src: SynsetId) -> Vec<Edge> {
            let mut out = Vec::new();
            let n = self.len();
            for i in 0..n {
                if read_u24(&self.sources, i) == src.0 {
                    if let Some(e) = self.get(i) {
                        out.push(e);
                    }
                }
            }
            out
        }

        /// Edges where `target == tgt`.
        pub fn incoming(&self, tgt: SynsetId) -> Vec<Edge> {
            let mut out = Vec::new();
            let n = self.len();
            for i in 0..n {
                if read_u24(&self.targets, i) == tgt.0 {
                    if let Some(e) = self.get(i) {
                        out.push(e);
                    }
                }
            }
            out
        }

        /// Serialize: ZEDG magic + version + u64 count + 4 columns.
        pub fn write_to<W: Write>(&self, w: &mut W) -> io::Result<()> {
            w.write_all(Self::MAGIC)?;
            w.write_all(&[Self::VERSION])?;
            let count = self.len() as u64;
            w.write_all(&count.to_le_bytes())?;
            w.write_all(&self.sources)?;
            w.write_all(&self.targets)?;
            w.write_all(&self.rel_weight)?;
            w.write_all(&self.provenance)?;
            Ok(())
        }

        /// Deserialize from reader.
        pub fn read_from<R: Read>(r: &mut R) -> io::Result<Self> {
            let mut magic = [0u8; 4];
            r.read_exact(&mut magic)?;
            if magic != *Self::MAGIC {
                return Err(io::Error::new(io::ErrorKind::InvalidData,
                    format!("bad magic: {magic:?}")));
            }
            let mut ver = [0u8; 1];
            r.read_exact(&mut ver)?;
            if ver[0] != Self::VERSION {
                return Err(io::Error::new(io::ErrorKind::InvalidData,
                    format!("unsupported version: {}", ver[0])));
            }
            let mut cb = [0u8; 8];
            r.read_exact(&mut cb)?;
            let count = u64::from_le_bytes(cb) as usize;

            let mut store = Self::with_capacity(count);
            store.sources.resize(count * 3, 0);
            store.targets.resize(count * 3, 0);
            store.rel_weight.resize(count, 0);
            store.provenance.resize(count * 3, 0);

            r.read_exact(&mut store.sources)?;
            r.read_exact(&mut store.targets)?;
            r.read_exact(&mut store.rel_weight)?;
            r.read_exact(&mut store.provenance)?;
            Ok(store)
        }
    }

    pub struct EdgeIter<'a> {
        store: &'a EdgeStore,
        pos: usize,
    }

    impl Iterator for EdgeIter<'_> {
        type Item = Edge;
        #[inline]
        fn next(&mut self) -> Option<Edge> {
            let e = self.store.get(self.pos)?;
            self.pos += 1;
            Some(e)
        }
    }

    // ========================================================================
    // ADJACENCY INDEX — sorted-edge binary search, O(log N) lookups
    // ========================================================================

    /// Auxiliary index for O(log N) lookups by source or target.
    ///
    /// Built on demand from an `EdgeStore`. Stores two permutations of edge
    /// indices: one sorted by source, one sorted by target. Each permutation
    /// is a `Vec<u32>` — 4 bytes per edge per direction, 8 bytes total overhead.
    ///
    /// # When to use
    ///
    /// Linear scan via `outgoing()`/`incoming()` is fine up to ~1M edges
    /// (measured: ~1ms per query). Above that, scan time dominates: 5M edges
    /// needs ~5ms per query, and multi-hop walks (depth 3, fanout 5) blow
    /// through the 100ms target.
    ///
    /// Build the index once after bulk loading, then use `outgoing_indexed()`
    /// and `incoming_indexed()` for fast walks.
    ///
    /// # Memory cost
    ///
    /// Index of 10M edges = 80MB RAM (2 × 4 bytes × 10M). For devices like
    /// Pi 5 with 8GB, this is acceptable. For phones, might want to index
    /// only frequently-walked direction.
    ///
    /// # Complexity
    ///
    /// - Build: O(N log N) — two sorts
    /// - Lookup: O(log N + K) — binary search + K matching edges
    ///
    /// # Rebuild policy
    ///
    /// Index is static. After `store.push()`, the index is stale. The
    /// maintenance cycle (idle-aware compaction, SPEC V6.1 §V) rebuilds it.
    #[derive(Debug, Clone)]
    pub struct AdjacencyIndex {
        /// Edge indices sorted by source synset ID (ascending).
        /// `by_source[i]` is the original position in the EdgeStore.
        by_source: Vec<u32>,
        /// Edge indices sorted by target synset ID (ascending).
        by_target: Vec<u32>,
    }

    impl AdjacencyIndex {
        /// Build a fresh index from the current state of an `EdgeStore`.
        ///
        /// Cost: O(N log N). For 1M edges: ~80ms on Oracle x86_64.
        #[must_use]
        pub fn build(store: &EdgeStore) -> Self {
            let n = store.len();
            let mut by_source: Vec<u32> = (0..u32::try_from(n).unwrap_or(u32::MAX)).collect();
            let mut by_target: Vec<u32> = by_source.clone();

            // Closures that read directly from packed columns.
            // No Vec<Edge> materialization — work on indices only.
            by_source.sort_unstable_by_key(|&i| read_u24(&store.sources, i as usize));
            by_target.sort_unstable_by_key(|&i| read_u24(&store.targets, i as usize));

            Self { by_source, by_target }
        }

        /// Bytes used by the index itself (excluding Vec overhead).
        ///
        /// Each index is `4 * edge_count` bytes; we have two indices.
        #[inline]
        #[must_use]
        pub fn bytes_used(&self) -> usize {
            (self.by_source.len() + self.by_target.len()) * 4
        }

        #[inline]
        #[must_use]
        pub fn edge_count(&self) -> usize {
            self.by_source.len()
        }

        /// Find the range `[lo, hi)` of `by_source` where the source equals `src`.
        /// Uses `partition_point` (binary search) twice — O(log N) total.
        fn source_range(&self, store: &EdgeStore, src: u32) -> (usize, usize) {
            let lo = self.by_source.partition_point(|&i| {
                read_u24(&store.sources, i as usize) < src
            });
            let hi = self.by_source.partition_point(|&i| {
                read_u24(&store.sources, i as usize) <= src
            });
            (lo, hi)
        }

        /// Find the range `[lo, hi)` of `by_target` where the target equals `tgt`.
        fn target_range(&self, store: &EdgeStore, tgt: u32) -> (usize, usize) {
            let lo = self.by_target.partition_point(|&i| {
                read_u24(&store.targets, i as usize) < tgt
            });
            let hi = self.by_target.partition_point(|&i| {
                read_u24(&store.targets, i as usize) <= tgt
            });
            (lo, hi)
        }

        /// Edges where `source == src`. O(log N + K).
        #[must_use]
        pub fn outgoing(&self, store: &EdgeStore, src: SynsetId) -> Vec<Edge> {
            let (lo, hi) = self.source_range(store, src.0);
            let mut out = Vec::with_capacity(hi - lo);
            for &edge_idx in &self.by_source[lo..hi] {
                if let Some(e) = store.get(edge_idx as usize) {
                    out.push(e);
                }
            }
            out
        }

        /// Edges where `target == tgt`. O(log N + K).
        #[must_use]
        pub fn incoming(&self, store: &EdgeStore, tgt: SynsetId) -> Vec<Edge> {
            let (lo, hi) = self.target_range(store, tgt.0);
            let mut out = Vec::with_capacity(hi - lo);
            for &edge_idx in &self.by_target[lo..hi] {
                if let Some(e) = store.get(edge_idx as usize) {
                    out.push(e);
                }
            }
            out
        }

        /// Count outgoing edges without materializing them. O(log N).
        #[must_use]
        pub fn outgoing_count(&self, store: &EdgeStore, src: SynsetId) -> usize {
            let (lo, hi) = self.source_range(store, src.0);
            hi - lo
        }

        /// Count incoming edges without materializing them. O(log N).
        #[must_use]
        pub fn incoming_count(&self, store: &EdgeStore, tgt: SynsetId) -> usize {
            let (lo, hi) = self.target_range(store, tgt.0);
            hi - lo
        }

        /// Find all distinct source synsets with at least one outgoing edge.
        /// O(N) first call, could be cached. Useful for graph statistics.
        #[must_use]
        pub fn distinct_sources(&self, store: &EdgeStore) -> Vec<SynsetId> {
            let mut out = Vec::new();
            let mut last: Option<u32> = None;
            for &i in &self.by_source {
                let s = read_u24(&store.sources, i as usize);
                if last != Some(s) {
                    out.push(SynsetId(s));
                    last = Some(s);
                }
            }
            out
        }
    }

}


// ============================================================================
// DOCUMENT — text as a sequence of tokens grounded in provenance
// ============================================================================

pub mod document {
    //! Text as a first-class graph structure.
    //!
    //! A document is not a flat bag of facts — it is an ordered sequence of
    //! tokens, each linked to the document it appears in. This lets the graph
    //! answer questions like:
    //!
    //! - "What word follows X in document D?" → `outgoing(X, TextNext, in D)`
    //! - "Where does X appear?" → `outgoing(X, AppearsIn)`
    //! - "What does document D reference?" → `outgoing(D, Cites)`
    //!
    //! # Layout
    //!
    //! For a document D and tokens `[t_0, t_1, t_2, ...]`:
    //!
    //! ```text
    //! t_0 --TEXT_NEXT(provenance=pos0)--> t_1
    //! t_1 --TEXT_NEXT(provenance=pos1)--> t_2
    //! ...
    //! t_0 --APPEARS_IN(provenance=pos0)--> D
    //! t_1 --APPEARS_IN(provenance=pos1)--> D
    //! ...
    //! ```
    //!
    //! Position is carried in the `provenance` field (u24, up to 16M positions
    //! per document — more than enough for a book).
    //!
    //! # Document synset IDs
    //!
    //! Documents live in the concept space (1_000_000+) so they don't collide
    //! with surface-form synsets (10_000..999_999).

    use super::edge_store::{Edge, EdgeStore, Relation};
    use super::SynsetId;

    /// First synset ID reserved for documents.
    pub const DOCUMENT_ID_START: u32 = 1_000_000;

    /// Document metadata (held in a separate registry).
    #[derive(Debug, Clone)]
    pub struct DocumentMeta {
        pub id: SynsetId,
        pub title: String,
        pub source_uri: String,
        pub token_count: u32,
    }

    /// Allocator for document IDs — produces monotonically increasing IDs
    /// starting from `DOCUMENT_ID_START`.
    #[derive(Debug)]
    pub struct DocumentIdAllocator {
        next: u32,
    }

    impl Default for DocumentIdAllocator {
        fn default() -> Self {
            Self { next: DOCUMENT_ID_START }
        }
    }

    impl DocumentIdAllocator {
        #[must_use]
        pub fn new() -> Self {
            Self::default()
        }

        /// Allocate the next document ID.
        #[inline]
        pub fn allocate(&mut self) -> SynsetId {
            let id = SynsetId(self.next);
            self.next += 1;
            id
        }

        #[inline]
        #[must_use]
        pub const fn count(&self) -> u32 {
            self.next - DOCUMENT_ID_START
        }
    }

    /// Add a token sequence to a graph.
    ///
    /// Creates two kinds of edges for each token at position `i`:
    /// 1. `tokens[i] --TEXT_NEXT--> tokens[i+1]` with provenance = `i`
    /// 2. `tokens[i] --APPEARS_IN--> doc` with provenance = `i`
    ///
    /// Returns the number of edges added. For N tokens this is `(N-1) + N = 2N-1`.
    ///
    /// # Parameters
    /// - `store`: mutable graph to append into
    /// - `doc`: document synset ID (from `DocumentIdAllocator`)
    /// - `tokens`: sequence of token synset IDs in document order
    ///
    /// # Example
    ///
    /// ```ignore
    /// let mut store = EdgeStore::new();
    /// let mut alloc = DocumentIdAllocator::new();
    /// let doc = alloc.allocate();
    /// let tokens = [SynsetId(10_001), SynsetId(10_002), SynsetId(10_003)];
    /// add_sequence(&mut store, doc, &tokens);
    /// // Now:
    /// //   outgoing(10_001, TEXT_NEXT) = [10_002] at pos 0
    /// //   outgoing(10_002, TEXT_NEXT) = [10_003] at pos 1
    /// //   outgoing(10_001, APPEARS_IN) = [doc] at pos 0
    /// ```
    pub fn add_sequence(store: &mut EdgeStore, doc: SynsetId, tokens: &[SynsetId]) -> usize {
        if tokens.is_empty() {
            return 0;
        }
        let mut count = 0;

        // Sequence edges: t_i --TEXT_NEXT--> t_{i+1}
        for i in 0..tokens.len().saturating_sub(1) {
            store.push(Edge {
                source: tokens[i],
                target: tokens[i + 1],
                relation: Relation::TextNext,
                weight: 7,
                provenance: u32::try_from(i).unwrap_or(u32::MAX),
            });
            count += 1;
        }

        // Membership edges: t_i --APPEARS_IN--> doc
        for (i, &tok) in tokens.iter().enumerate() {
            store.push(Edge {
                source: tok,
                target: doc,
                relation: Relation::AppearsIn,
                weight: 7,
                provenance: u32::try_from(i).unwrap_or(u32::MAX),
            });
            count += 1;
        }

        count
    }

    /// Record that document `from` cites document `to` (reference / quotation /
    /// hyperlink). `weight` represents confidence of the citation relationship
    /// (0-7); use 7 for direct explicit citations, lower for inferred.
    #[inline]
    pub fn add_citation(store: &mut EdgeStore, from: SynsetId, to: SynsetId, weight: u8) {
        store.push(Edge {
            source: from,
            target: to,
            relation: Relation::Cites,
            weight,
            provenance: 0,
        });
    }

    /// Reconstruct the ordered token sequence of a document by walking
    /// `APPEARS_IN` edges sorted by position (provenance).
    ///
    /// This is O(N) in total edges — Week 3 will add an index for O(log N).
    /// Use for verification, not hot paths.
    #[must_use]
    pub fn reconstruct_sequence(store: &EdgeStore, doc: SynsetId) -> Vec<(u32, SynsetId)> {
        let mut tokens: Vec<(u32, SynsetId)> = store
            .incoming(doc)
            .into_iter()
            .filter(|e| e.relation == Relation::AppearsIn)
            .map(|e| (e.provenance, e.source))
            .collect();
        tokens.sort_by_key(|&(pos, _)| pos);
        tokens
    }

    /// What word follows `token` in any document? Returns list of (doc-position,
    /// next-token) pairs across all documents where `token` appears.
    #[must_use]
    pub fn next_tokens(store: &EdgeStore, token: SynsetId) -> Vec<(u32, SynsetId)> {
        store
            .outgoing(token)
            .into_iter()
            .filter(|e| e.relation == Relation::TextNext)
            .map(|e| (e.provenance, e.target))
            .collect()
    }

    /// What documents does `doc` cite?
    #[must_use]
    pub fn citations(store: &EdgeStore, doc: SynsetId) -> Vec<SynsetId> {
        store
            .outgoing(doc)
            .into_iter()
            .filter(|e| e.relation == Relation::Cites)
            .map(|e| e.target)
            .collect()
    }

    /// What documents cite `doc`? (reverse citation)
    #[must_use]
    pub fn cited_by(store: &EdgeStore, doc: SynsetId) -> Vec<SynsetId> {
        store
            .incoming(doc)
            .into_iter()
            .filter(|e| e.relation == Relation::Cites)
            .map(|e| e.source)
            .collect()
    }
}

// ============================================================================
// LEARNING — ingest vocabulary/dictionary data into the graph
// ============================================================================

pub mod learning {
    //! Ingest structured lexical data (TSV) into an EdgeStore.
    //!
    //! The input format is a simple tab-separated dictionary:
    //!   surface<TAB>synset_id<TAB>pos<TAB>english_gloss<TAB>definition<TAB>synonyms
    //!
    //! Synonyms are semicolon-separated references to other surfaces in the
    //! same file. Missing fields are OK (empty string).
    //!
    //! # Output edges
    //!
    //! Each entry produces multiple edges:
    //!
    //! 1. `concept --IS_A--> part-of-speech-concept` (classifies word type)
    //! 2. `concept --SAME_AS--> english-concept` (translation, cross-language)
    //! 3. `concept --DEFINED_BY--> definition-concept` (gloss as concept)
    //! 4. `concept --NEAR_SYNONYM--> synonym-concept` (Hebrew synonymy)
    //!
    //! # Trust-ordered learning
    //!
    //! The caller chooses ingestion order. Recommended sequence:
    //!   Tier 1: core vocabulary (~300 words) — highest trust, verified by hand
    //!   Tier 2: Dicta/YAP dictionary (~5K-30K) — high trust, linguistic authority
    //!   Tier 3: Wikipedia lemmas (~500K) — medium trust, cross-referenced
    //!   Tier 4: web extraction — lowest trust, requires verification
    //!
    //! Weight field encodes trust: 7=Tier1, 6=Tier2, 5=Tier3, 3=Tier4.

    use super::edge_store::{Edge, EdgeStore, Relation};
    use super::{LangCode, SynsetId};
    use std::collections::HashMap;

    /// Trust tier for an ingestion batch. Maps to edge weight.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum Tier {
        /// Hand-verified core vocabulary. weight = 7.
        Tier1Core = 7,
        /// Linguistic authority (Dicta, YAP, WordNet). weight = 6.
        Tier2Authority = 6,
        /// Cross-referenced corpus (Wikipedia). weight = 5.
        Tier3Corpus = 5,
        /// Web extraction, needs verification. weight = 3.
        Tier4Unverified = 3,
    }

    impl Tier {
        #[inline]
        #[must_use]
        pub const fn weight(self) -> u8 {
            self as u8
        }

        #[must_use]
        pub const fn name(self) -> &'static str {
            match self {
                Self::Tier1Core => "core",
                Self::Tier2Authority => "authority",
                Self::Tier3Corpus => "corpus",
                Self::Tier4Unverified => "unverified",
            }
        }
    }

    /// A single parsed lexicon entry.
    #[derive(Debug, Clone)]
    pub struct LexEntry {
        pub surface: String,
        pub synset_id: SynsetId,
        pub pos: String,
        pub english: String,
        pub definition: String,
        pub synonyms: Vec<String>,
    }

    /// Summary of an ingestion operation.
    #[derive(Debug, Clone, Default)]
    pub struct IngestStats {
        pub entries_read: usize,
        pub edges_added: usize,
        pub synonym_edges: usize,
        pub translation_edges: usize,
        pub definition_edges: usize,
        pub pos_edges: usize,
        pub synsets_allocated: usize,
        pub unresolved_synonyms: usize,
    }

    /// Parse a TSV lexicon file into entries. Skips comments and blank lines.
    ///
    /// # Errors
    /// Returns `Err` if a line has fewer than 2 fields or if synset_id can't
    /// be parsed as u32.
    pub fn parse_tsv(content: &str) -> Result<Vec<LexEntry>, String> {
        let mut out = Vec::new();
        for (lineno, raw) in content.lines().enumerate() {
            let line = raw.trim_end();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let fields: Vec<&str> = line.split('\t').collect();
            if fields.len() < 2 {
                return Err(format!("line {}: too few fields", lineno + 1));
            }
            let synset_id: u32 = fields[1].parse()
                .map_err(|e| format!("line {}: bad synset_id: {e}", lineno + 1))?;

            let synonyms: Vec<String> = fields.get(5)
                .map(|s| s.split(';')
                    .map(str::trim)
                    .filter(|s| !s.is_empty())
                    .map(String::from)
                    .collect())
                .unwrap_or_default();

            out.push(LexEntry {
                surface: fields[0].to_string(),
                synset_id: SynsetId(synset_id),
                pos: fields.get(2).unwrap_or(&"").to_string(),
                english: fields.get(3).unwrap_or(&"").to_string(),
                definition: fields.get(4).unwrap_or(&"").to_string(),
                synonyms,
            });
        }
        Ok(out)
    }

    /// Allocator for synsets created on the fly (English translations,
    /// definitions, parts-of-speech as concept nodes).
    pub struct AuxSynsetAllocator {
        next: u32,
        keys: HashMap<String, SynsetId>,
    }

    impl AuxSynsetAllocator {
        /// Start at 3_000_000 — above documents (1M) and concepts (2M).
        pub const AUX_START: u32 = 3_000_000;

        #[must_use]
        pub fn new() -> Self {
            Self {
                next: Self::AUX_START,
                keys: HashMap::new(),
            }
        }

        /// Get or allocate a synset for a given key. Idempotent.
        pub fn get_or_alloc(&mut self, key: &str) -> SynsetId {
            if let Some(&id) = self.keys.get(key) {
                return id;
            }
            let id = SynsetId(self.next);
            self.next += 1;
            self.keys.insert(key.to_string(), id);
            id
        }

        #[inline]
        #[must_use]
        pub fn count(&self) -> usize {
            self.keys.len()
        }
    }

    impl Default for AuxSynsetAllocator {
        fn default() -> Self { Self::new() }
    }

    /// Ingest a parsed lexicon into an EdgeStore.
    ///
    /// Builds a surface→synset map on the fly for synonym resolution.
    /// Returns detailed statistics.
    pub fn ingest(
        store: &mut EdgeStore,
        aux: &mut AuxSynsetAllocator,
        entries: &[LexEntry],
        _lang: LangCode,
        tier: Tier,
    ) -> IngestStats {
        let weight = tier.weight();

        // Build surface→synset map for local synonym resolution
        let mut by_surface: HashMap<&str, SynsetId> = HashMap::new();
        for e in entries {
            by_surface.insert(e.surface.as_str(), e.synset_id);
        }

        let mut stats = IngestStats { entries_read: entries.len(), ..Default::default() };

        for entry in entries {
            // 1. Part-of-speech classification: word IS_A pos-concept
            if !entry.pos.is_empty() {
                let pos_synset = aux.get_or_alloc(&format!("pos:{}", entry.pos));
                store.push(Edge {
                    source: entry.synset_id,
                    target: pos_synset,
                    relation: Relation::IsA,
                    weight,
                    provenance: 0,
                });
                stats.edges_added += 1;
                stats.pos_edges += 1;
            }

            // 2. English translation: concept SAME_AS english-concept
            if !entry.english.is_empty() {
                let en_synset = aux.get_or_alloc(&format!("en:{}", entry.english));
                store.push(Edge {
                    source: entry.synset_id,
                    target: en_synset,
                    relation: Relation::SameAs,
                    weight,
                    provenance: 0,
                });
                stats.edges_added += 1;
                stats.translation_edges += 1;
            }

            // 3. Definition: concept DEFINED_BY definition-text-concept
            if !entry.definition.is_empty() {
                let def_synset = aux.get_or_alloc(&format!("def:{}", entry.definition));
                store.push(Edge {
                    source: entry.synset_id,
                    target: def_synset,
                    relation: Relation::DefinedBy,
                    weight,
                    provenance: 0,
                });
                stats.edges_added += 1;
                stats.definition_edges += 1;
            }

            // 4. Synonyms: concept NEAR_SYNONYM synonym-concept
            for syn in &entry.synonyms {
                if let Some(&syn_id) = by_surface.get(syn.as_str()) {
                    store.push(Edge {
                        source: entry.synset_id,
                        target: syn_id,
                        relation: Relation::NearSynonym,
                        weight,
                        provenance: 0,
                    });
                    stats.edges_added += 1;
                    stats.synonym_edges += 1;
                } else {
                    // Synonym not in this batch — allocate aux synset, still link
                    let syn_id = aux.get_or_alloc(&format!("syn:{syn}"));
                    store.push(Edge {
                        source: entry.synset_id,
                        target: syn_id,
                        relation: Relation::NearSynonym,
                        weight: weight.saturating_sub(1),  // lower weight — unresolved
                        provenance: 0,
                    });
                    stats.edges_added += 1;
                    stats.synonym_edges += 1;
                    stats.unresolved_synonyms += 1;
                }
            }
        }

        stats.synsets_allocated = aux.count();
        stats
    }

    /// Build a surface→synset lookup map from parsed entries.
    /// This is what the UNP Week 3 dictionary would consume.
    #[must_use]
    pub fn build_surface_map(entries: &[LexEntry]) -> HashMap<String, SynsetId> {
        let mut map = HashMap::with_capacity(entries.len());
        for e in entries {
            map.insert(e.surface.clone(), e.synset_id);
        }
        map
    }

    /// Find all synonyms of a word by walking NEAR_SYNONYM edges.
    /// Returns a list of synset IDs, sorted deterministically.
    #[must_use]
    pub fn find_synonyms(store: &EdgeStore, word: SynsetId) -> Vec<SynsetId> {
        let mut out: Vec<SynsetId> = store.outgoing(word)
            .into_iter()
            .filter(|e| e.relation == Relation::NearSynonym)
            .map(|e| e.target)
            .collect();
        out.sort_by_key(|s| s.0);
        out.dedup();
        out
    }

    /// Find the English translation of a word by following SAME_AS edges.
    /// (Multiple allowed; returns all.)
    #[must_use]
    pub fn find_translations(store: &EdgeStore, word: SynsetId) -> Vec<SynsetId> {
        let mut out: Vec<SynsetId> = store.outgoing(word)
            .into_iter()
            .filter(|e| e.relation == Relation::SameAs)
            .map(|e| e.target)
            .collect();
        out.sort_by_key(|s| s.0);
        out
    }
}

// ============================================================================
// BLOOM FILTER — custom implementation, 80 lines
// ============================================================================

pub mod bloom {
    //! Custom Bloom filter — FNV-1a with Kirsch-Mitzenmacher double-hashing.
    //!
    //! Default: 8 MiB bitmap, 7 hashes. Good for ~1M items, <1% FP rate.

    pub const DEFAULT_BITS: usize = 8 * 1024 * 1024 * 8;
    pub const DEFAULT_HASHES: u8 = 7;

    pub struct BloomFilter {
        bits: Vec<u8>,
        num_bits: usize,
        num_hashes: u8,
    }

    impl BloomFilter {
        #[must_use]
        pub fn new(num_bits: usize, num_hashes: u8) -> Self {
            Self {
                bits: vec![0u8; num_bits.div_ceil(8)],
                num_bits,
                num_hashes,
            }
        }

        #[must_use]
        pub fn default_size() -> Self {
            Self::new(DEFAULT_BITS, DEFAULT_HASHES)
        }

        #[inline]
        pub fn bytes_used(&self) -> usize {
            self.bits.len()
        }

        pub fn insert(&mut self, key: &[u8]) {
            let (h1, h2) = Self::double_hash(key);
            for i in 0..self.num_hashes {
                let idx = self.bit_index(h1, h2, i);
                self.set_bit(idx);
            }
        }

        #[inline]
        pub fn might_contain(&self, key: &[u8]) -> bool {
            let (h1, h2) = Self::double_hash(key);
            for i in 0..self.num_hashes {
                let idx = self.bit_index(h1, h2, i);
                if !self.get_bit(idx) {
                    return false;
                }
            }
            true
        }

        pub fn bits_set(&self) -> usize {
            self.bits.iter().map(|b| b.count_ones() as usize).sum()
        }

        pub fn estimated_fp_rate(&self) -> f64 {
            let ratio = self.bits_set() as f64 / self.num_bits as f64;
            ratio.powi(i32::from(self.num_hashes))
        }

        #[inline]
        fn double_hash(key: &[u8]) -> (u64, u64) {
            (fnv1a_64(key, 0xcbf2_9ce4_8422_2325),
             fnv1a_64(key, 0x8422_2325_cbf2_9ce4))
        }

        #[inline]
        fn bit_index(&self, h1: u64, h2: u64, i: u8) -> usize {
            let combined = h1.wrapping_add(u64::from(i).wrapping_mul(h2));
            (combined as usize) % self.num_bits
        }

        #[inline]
        fn set_bit(&mut self, idx: usize) {
            self.bits[idx / 8] |= 1 << (idx % 8);
        }

        #[inline]
        fn get_bit(&self, idx: usize) -> bool {
            (self.bits[idx / 8] >> (idx % 8)) & 1 == 1
        }
    }

    #[inline]
    fn fnv1a_64(data: &[u8], seed: u64) -> u64 {
        const PRIME: u64 = 0x100_0000_01b3;
        let mut hash = seed;
        for &b in data {
            hash ^= u64::from(b);
            hash = hash.wrapping_mul(PRIME);
        }
        hash
    }
}

// ============================================================================
// CLI
#[cfg(test)]
mod tests {
    use super::*;
    use super::edge_store::{Edge, EdgeStore, Relation};
    use std::io::Cursor;
    use super::bloom::BloomFilter;

    // --- LangCode ---

    #[test]
    fn langcode_constants_correct() {
        assert_eq!(LangCode::HEBREW.as_str(), "he");
        assert_eq!(LangCode::ENGLISH.as_str(), "en");
        assert_eq!(LangCode::ARABIC.as_str(), "ar");
        assert_eq!(LangCode::CHINESE.as_str(), "cn");
    }

    #[test]
    fn langcode_parse_case_insensitive() {
        assert_eq!(LangCode::parse("he"), Some(LangCode::HEBREW));
        assert_eq!(LangCode::parse("HE"), Some(LangCode::HEBREW));
        assert_eq!(LangCode::parse("He"), Some(LangCode::HEBREW));
    }

    #[test]
    fn langcode_parse_rejects_invalid() {
        assert_eq!(LangCode::parse(""), None);
        assert_eq!(LangCode::parse("h"), None);
        assert_eq!(LangCode::parse("heb"), None);
        assert_eq!(LangCode::parse("h3"), None);
        assert_eq!(LangCode::parse("12"), None);
    }

    #[test]
    fn langcode_meta_lookup() {
        let he = LangCode::HEBREW.meta().unwrap();
        assert_eq!(he.name_english, "Hebrew");
        assert!(he.rtl);
        assert!(he.default_active);
    }

    #[test]
    fn langcode_unknown_no_meta() {
        let xx = LangCode::parse("xx").unwrap();
        assert!(xx.meta().is_none());
    }

    #[test]
    fn langcode_is_rtl() {
        assert!(LangCode::HEBREW.is_rtl());
        assert!(LangCode::ARABIC.is_rtl());
        assert!(!LangCode::ENGLISH.is_rtl());
    }

    // --- UNP determinism ---

    #[test]
    fn determinism_identical_inputs() {
        let a = unp::normalize("הבית הגדול", LangCode::HEBREW);
        let b = unp::normalize("הבית הגדול", LangCode::HEBREW);
        assert_eq!(a.as_bytes(), b.as_bytes());
    }

    #[test]
    fn determinism_across_many_iterations() {
        let cases = [
            ("כלב", LangCode::HEBREW),
            ("Hello", LangCode::ENGLISH),
            ("محمد", LangCode::ARABIC),
        ];
        for (input, lang) in &cases {
            let first = unp::normalize(input, *lang);
            for _ in 0..50 {
                let again = unp::normalize(input, *lang);
                assert_eq!(first.as_bytes(), again.as_bytes(),
                    "non-deterministic: {input} in {lang:?}");
            }
        }
    }

    // --- Hebrew module ---

    #[test]
    fn hebrew_is_niqud_detects_common() {
        assert!(hebrew::is_niqud('ַ'));
        assert!(hebrew::is_niqud('ִ'));
        assert!(hebrew::is_niqud('ֹ'));
        assert!(hebrew::is_niqud('ּ'));
    }

    #[test]
    fn hebrew_is_niqud_rejects_letters() {
        assert!(!hebrew::is_niqud('ב'));
        assert!(!hebrew::is_niqud('ש'));
    }

    #[test]
    fn hebrew_final_form_normalization() {
        assert_eq!(hebrew::normalize_final_form('ך'), 'כ');
        assert_eq!(hebrew::normalize_final_form('ם'), 'מ');
        assert_eq!(hebrew::normalize_final_form('ן'), 'נ');
        assert_eq!(hebrew::normalize_final_form('ף'), 'פ');
        assert_eq!(hebrew::normalize_final_form('ץ'), 'צ');
        assert_eq!(hebrew::normalize_final_form('ב'), 'ב');
    }

    #[test]
    fn hebrew_canonicalize_empty() {
        assert_eq!(hebrew::canonicalize(""), "");
        assert_eq!(hebrew::canonicalize("   "), "");
    }

    #[test]
    fn hebrew_canonicalize_preserves_non_hebrew() {
        assert_eq!(hebrew::canonicalize("hello"), "hello");
    }

    #[test]
    fn hebrew_canonicalize_normalizes_final() {
        assert_eq!(hebrew::canonicalize("מלך"), "מלכ");
        assert_eq!(hebrew::canonicalize("שלום"), "שלומ");
    }

    #[test]
    fn hebrew_aggressive_stem_long_words() {
        assert_eq!(hebrew::aggressive_stem_fallback("הכלבים"), "כלב");
    }

    #[test]
    fn hebrew_aggressive_stem_preserves_short() {
        assert_eq!(hebrew::aggressive_stem_fallback("בית"), "בית");
    }

    // --- Test vector table ---

    #[test]
    fn all_week1_test_vectors_pass() {
        let mut failures = Vec::new();
        for v in TEST_VECTORS {
            if v.category == "needs_dict" { continue; }
            let lang = LangCode::parse(v.lang).expect("valid lang in test data");
            let result = unp::normalize(v.input, lang);
            if result.as_str() != v.expected {
                failures.push(format!("{} input={:?} expected={:?} got={:?} ({})",
                    v.lang, v.input, v.expected, result.as_str(), v.note));
            }
        }
        assert!(failures.is_empty(), "{} vectors failed:\n{}",
            failures.len(), failures.join("\n"));
    }

    // --- Meta-graph ---

    #[test]
    fn meta_graph_lookup_by_key() {
        let he = meta_graph::by_key("he").expect("he synset exists");
        assert_eq!(he.0, 10);
        let is_a = meta_graph::by_key("IS_A").expect("IS_A synset exists");
        assert_eq!(is_a.0, 30);
    }

    #[test]
    fn meta_graph_by_category() {
        let langs = meta_graph::by_category("language");
        assert_eq!(langs.len(), 10);
        let rels = meta_graph::by_category("relation");
        assert_eq!(rels.len(), 30); // 27 enum relations + 3 graph-only meta-relations
    }

    #[test]
    fn meta_graph_known_languages() {
        let codes = meta_graph::known_language_codes();
        assert!(codes.contains(&"he"));
        assert!(codes.contains(&"en"));
        assert!(codes.contains(&"cn"));
    }

    // --- EdgeStore ---

    #[test]
    fn edge_store_empty() {
        let store = EdgeStore::new();
        assert_eq!(store.len(), 0);
        assert!(store.is_empty());
    }

    #[test]
    fn edge_store_push_get() {
        let mut store = EdgeStore::new();
        let edge = Edge { source: SynsetId(12345), target: SynsetId(67890),
            relation: Relation::IsA, weight: 5, provenance: 999 };
        let idx = store.push(edge);
        assert_eq!(idx, 0);
        assert_eq!(store.get(0), Some(edge));
    }

    #[test]
    fn edge_store_max_u24() {
        let mut store = EdgeStore::new();
        let edge = Edge { source: SynsetId(SynsetId::MAX), target: SynsetId(SynsetId::MAX),
            relation: Relation::OpposedTo, weight: 7, provenance: SynsetId::MAX };
        store.push(edge);
        assert_eq!(store.get(0), Some(edge));
    }

    #[test]
    fn edge_store_byte_layout() {
        let mut store = EdgeStore::new();
        for i in 0..100 {
            store.push(Edge { source: SynsetId(i), target: SynsetId(i+1),
                relation: Relation::IsA, weight: 0, provenance: 0 });
        }
        assert_eq!(store.bytes_used(), 1000); // 100 * 10
    }

    #[test]
    fn edge_store_outgoing() {
        let mut store = EdgeStore::new();
        store.push(Edge { source: SynsetId(1), target: SynsetId(10),
            relation: Relation::IsA, weight: 0, provenance: 0 });
        store.push(Edge { source: SynsetId(2), target: SynsetId(20),
            relation: Relation::IsA, weight: 0, provenance: 0 });
        store.push(Edge { source: SynsetId(1), target: SynsetId(30),
            relation: Relation::HasPart, weight: 0, provenance: 0 });
        assert_eq!(store.outgoing(SynsetId(1)).len(), 2);
        assert_eq!(store.outgoing(SynsetId(2)).len(), 1);
        assert_eq!(store.outgoing(SynsetId(999)).len(), 0);
    }

    #[test]
    fn edge_store_serialize_roundtrip() {
        let mut store = EdgeStore::new();
        for i in 0..1000 {
            store.push(Edge { source: SynsetId(i), target: SynsetId(i * 2),
                relation: Relation::from_u8((i % 27) as u8).unwrap(),
                weight: (i % 8) as u8, provenance: i + 1 });
        }
        let mut buf = Vec::new();
        store.write_to(&mut buf).unwrap();
        let loaded = EdgeStore::read_from(&mut Cursor::new(&buf)).unwrap();
        assert_eq!(loaded.len(), store.len());
        for i in 0..1000 {
            assert_eq!(loaded.get(i), store.get(i));
        }
    }

    #[test]
    fn edge_store_relation_all_values() {
        let mut store = EdgeStore::new();
        for rv in 0..=Relation::MAX_VALUE {
            for w in 0..=7u8 {
                store.push(Edge { source: SynsetId(0), target: SynsetId(0),
                    relation: Relation::from_u8(rv).unwrap(),
                    weight: w, provenance: 0 });
            }
        }
        let mut idx = 0;
        for rv in 0..=Relation::MAX_VALUE {
            for w in 0..=7u8 {
                let e = store.get(idx).unwrap();
                assert_eq!(e.relation as u8, rv);
                assert_eq!(e.weight, w);
                idx += 1;
            }
        }
    }

    #[test]
    fn edge_store_new_with_meta_seeds_system() {
        let store = EdgeStore::new_with_meta();
        assert!(store.len() > 0);
        // Every language node should have MEMBER_OF edge to LANGUAGE_REGISTRY
        let he = meta_graph::by_key("he").unwrap();
        let edges = store.outgoing(he);
        assert!(edges.iter().any(|e| e.target == SynsetId::LANGUAGE_REGISTRY
            && e.relation == Relation::MemberOf));
    }

    #[test]
    fn relation_as_synset_homoiconic() {
        // IS_A relation itself is synset 30
        assert_eq!(Relation::IsA.as_synset(), SynsetId(30));
        assert_eq!(Relation::OpposedTo.as_synset(), SynsetId(56));
    }

    #[test]
    fn relation_inverse() {
        assert_eq!(Relation::HasPart.inverse(), Some(Relation::MemberOf));
        assert_eq!(Relation::IsA.inverse(), Some(Relation::ExampleOf));
        assert_eq!(Relation::Causes.inverse(), None);
    }

    // --- Bloom ---

    #[test]
    fn bloom_inserted_items_found() {
        let mut f = BloomFilter::default_size();
        for item in &["hello", "world", "כלב", "בית"] {
            f.insert(item.as_bytes());
        }
        for item in &["hello", "world", "כלב", "בית"] {
            assert!(f.might_contain(item.as_bytes()));
        }
    }

    #[test]
    fn bloom_empty_rejects() {
        let f = BloomFilter::default_size();
        assert!(!f.might_contain(b"anything"));
    }

    #[test]
    fn bloom_idempotent_insert() {
        let mut f = BloomFilter::default_size();
        f.insert(b"item");
        let b1 = f.bits_set();
        f.insert(b"item");
        assert_eq!(b1, f.bits_set());
    }

    #[test]
    fn bloom_fp_rate_acceptable() {
        let mut f = BloomFilter::default_size();
        for i in 0..10_000 {
            f.insert(format!("p_{i}").as_bytes());
        }
        let mut fp = 0;
        for i in 0..10_000 {
            if f.might_contain(format!("a_{i}").as_bytes()) { fp += 1; }
        }
        let rate = fp as f64 / 10_000.0;
        assert!(rate < 0.05, "FP rate too high: {rate}");
    }

    // --- Property: idempotence ---

    #[test]
    fn unp_idempotence_hebrew() {
        let inputs = ["כלב", "הבית", "שָׁלוֹם", "הכלבים", "  בית  "];
        for input in &inputs {
            let once = unp::normalize(input, LangCode::HEBREW);
            let twice = unp::normalize(once.as_str(), LangCode::HEBREW);
            assert_eq!(once.as_bytes(), twice.as_bytes());
        }
    }

    #[test]
    fn unp_idempotence_english() {
        for input in &["Hello", "WORLD", "  Hello  World  "] {
            let once = unp::normalize(input, LangCode::ENGLISH);
            let twice = unp::normalize(once.as_str(), LangCode::ENGLISH);
            assert_eq!(once.as_bytes(), twice.as_bytes());
        }
    }

    #[test]
    fn unp_no_panic_on_edge_inputs() {
        let _ = unp::normalize("", LangCode::HEBREW);
        let _ = unp::normalize("   \t\n   ", LangCode::HEBREW);
        let _ = unp::normalize("ַָֹּ", LangCode::HEBREW);
        let _ = unp::normalize("hello כלב 123", LangCode::HEBREW);
    }
    // --- Document module ---

    #[test]
    fn document_add_sequence_creates_correct_edges() {
        use super::document::{self, DocumentIdAllocator};
        let mut store = EdgeStore::new();
        let mut alloc = DocumentIdAllocator::new();
        let doc = alloc.allocate();
        let tokens = [SynsetId(10_001), SynsetId(10_002), SynsetId(10_003)];
        let edges = document::add_sequence(&mut store, doc, &tokens);
        assert_eq!(edges, 5); // 2 TEXT_NEXT + 3 APPEARS_IN
        assert_eq!(store.len(), 5);
    }

    #[test]
    fn document_reconstruct_preserves_order() {
        use super::document::{self, DocumentIdAllocator};
        let mut store = EdgeStore::new();
        let mut alloc = DocumentIdAllocator::new();
        let doc = alloc.allocate();
        let tokens = [SynsetId(10_001), SynsetId(10_002), SynsetId(10_003), SynsetId(10_004)];
        document::add_sequence(&mut store, doc, &tokens);
        let recon = document::reconstruct_sequence(&store, doc);
        assert_eq!(recon.len(), 4);
        assert_eq!(recon[0], (0, SynsetId(10_001)));
        assert_eq!(recon[1], (1, SynsetId(10_002)));
        assert_eq!(recon[2], (2, SynsetId(10_003)));
        assert_eq!(recon[3], (3, SynsetId(10_004)));
    }

    #[test]
    fn document_citations_bidirectional() {
        use super::document::{self, DocumentIdAllocator};
        let mut store = EdgeStore::new();
        let mut alloc = DocumentIdAllocator::new();
        let doc_a = alloc.allocate();
        let doc_b = alloc.allocate();
        document::add_citation(&mut store, doc_a, doc_b, 7);
        assert_eq!(document::citations(&store, doc_a), vec![doc_b]);
        assert_eq!(document::cited_by(&store, doc_b), vec![doc_a]);
    }

    #[test]
    fn document_empty_sequence_adds_no_edges() {
        use super::document::{self, DocumentIdAllocator};
        let mut store = EdgeStore::new();
        let mut alloc = DocumentIdAllocator::new();
        let doc = alloc.allocate();
        let edges = document::add_sequence(&mut store, doc, &[]);
        assert_eq!(edges, 0);
        assert_eq!(store.len(), 0);
    }

    #[test]
    fn document_allocator_monotonic() {
        use super::document::{DocumentIdAllocator, DOCUMENT_ID_START};
        let mut alloc = DocumentIdAllocator::new();
        assert_eq!(alloc.allocate(), SynsetId(DOCUMENT_ID_START));
        assert_eq!(alloc.allocate(), SynsetId(DOCUMENT_ID_START + 1));
        assert_eq!(alloc.allocate(), SynsetId(DOCUMENT_ID_START + 2));
        assert_eq!(alloc.count(), 3);
    }

    // --- Learning module ---

    #[test]
    fn learning_parse_tsv_rejects_bad_lines() {
        use super::learning;
        let bad = "only_one_field\n";
        assert!(learning::parse_tsv(bad).is_err());
    }

    #[test]
    fn learning_parse_tsv_skips_comments_and_blanks() {
        use super::learning;
        let input = "# comment\n\nword\t100\tnoun\tword\tdef\tsyn1;syn2\n";
        let entries = learning::parse_tsv(input).unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].surface, "word");
        assert_eq!(entries[0].synset_id, SynsetId(100));
        assert_eq!(entries[0].synonyms, vec!["syn1", "syn2"]);
    }

    #[test]
    fn learning_ingest_produces_expected_edges() {
        use super::learning::{self, Tier, AuxSynsetAllocator};
        let input = "כלב\t100\tnoun\tdog\tbeast\t\n";
        let entries = learning::parse_tsv(input).unwrap();
        let mut store = EdgeStore::new();
        let mut aux = AuxSynsetAllocator::new();
        let stats = learning::ingest(&mut store, &mut aux, &entries, LangCode::HEBREW, Tier::Tier1Core);
        assert_eq!(stats.entries_read, 1);
        assert_eq!(stats.pos_edges, 1);
        assert_eq!(stats.translation_edges, 1);
        assert_eq!(stats.definition_edges, 1);
        assert_eq!(stats.synonym_edges, 0);
        assert_eq!(stats.edges_added, 3);
    }

    #[test]
    fn learning_tier_weights() {
        use super::learning::Tier;
        assert_eq!(Tier::Tier1Core.weight(), 7);
        assert_eq!(Tier::Tier2Authority.weight(), 6);
        assert_eq!(Tier::Tier3Corpus.weight(), 5);
        assert_eq!(Tier::Tier4Unverified.weight(), 3);
    }

    #[test]
    fn learning_aux_allocator_is_idempotent() {
        use super::learning::AuxSynsetAllocator;
        let mut aux = AuxSynsetAllocator::new();
        let a = aux.get_or_alloc("pos:noun");
        let b = aux.get_or_alloc("pos:noun");
        let c = aux.get_or_alloc("pos:verb");
        assert_eq!(a, b);
        assert_ne!(a, c);
        assert_eq!(aux.count(), 2);
    }

    #[test]
    fn learning_find_synonyms_deterministic() {
        use super::learning::{self, Tier, AuxSynsetAllocator};
        let input = "חבר\t100\tnoun\tfriend\tcomrade\tידיד;רע\nידיד\t101\tnoun\tfriend\tcomrade\t\nרע\t102\tnoun\tfriend\tcompanion\t\n";
        let entries = learning::parse_tsv(input).unwrap();
        let mut store = EdgeStore::new();
        let mut aux = AuxSynsetAllocator::new();
        learning::ingest(&mut store, &mut aux, &entries, LangCode::HEBREW, Tier::Tier1Core);
        let syns = learning::find_synonyms(&store, SynsetId(100));
        assert!(syns.contains(&SynsetId(101)));
        assert!(syns.contains(&SynsetId(102)));
        // Determinism: calling twice returns same order
        let syns2 = learning::find_synonyms(&store, SynsetId(100));
        assert_eq!(syns, syns2);
    }

    // --- Relation type: new discourse relations ---

    #[test]
    fn new_relations_available() {
        use super::edge_store::Relation;
        assert_eq!(Relation::from_u8(27), Some(Relation::TextNext));
        assert_eq!(Relation::from_u8(28), Some(Relation::AppearsIn));
        assert_eq!(Relation::from_u8(29), Some(Relation::Cites));
        assert_eq!(Relation::from_u8(30), None);
        assert_eq!(Relation::MAX_VALUE, 29);
    }

    // --- AdjacencyIndex ---

    #[test]
    fn adjacency_index_matches_linear_scan_outgoing() {
        use super::edge_store::{AdjacencyIndex, Edge, EdgeStore, Relation};
        let mut store = EdgeStore::new();
        for i in 0..1000u32 {
            store.push(Edge {
                source: SynsetId(i % 100),
                target: SynsetId(i * 3),
                relation: Relation::IsA,
                weight: 0, provenance: 0,
            });
        }
        let idx = AdjacencyIndex::build(&store);
        for src in [0u32, 1, 50, 99] {
            let linear = store.outgoing(SynsetId(src));
            let indexed = idx.outgoing(&store, SynsetId(src));
            let mut l = linear.clone(); let mut i = indexed.clone();
            l.sort_by_key(|e| (e.source.0, e.target.0));
            i.sort_by_key(|e| (e.source.0, e.target.0));
            assert_eq!(l, i, "mismatch for source {src}");
        }
    }

    #[test]
    fn adjacency_index_matches_linear_scan_incoming() {
        use super::edge_store::{AdjacencyIndex, Edge, EdgeStore, Relation};
        let mut store = EdgeStore::new();
        for i in 0..1000u32 {
            store.push(Edge {
                source: SynsetId(i),
                target: SynsetId(i % 50),
                relation: Relation::IsA,
                weight: 0, provenance: 0,
            });
        }
        let idx = AdjacencyIndex::build(&store);
        for tgt in [0u32, 25, 49] {
            let linear = store.incoming(SynsetId(tgt));
            let indexed = idx.incoming(&store, SynsetId(tgt));
            assert_eq!(linear.len(), indexed.len(), "count mismatch for target {tgt}");
        }
    }

    #[test]
    fn adjacency_index_empty_source_returns_empty() {
        use super::edge_store::{AdjacencyIndex, Edge, EdgeStore, Relation};
        let mut store = EdgeStore::new();
        store.push(Edge {
            source: SynsetId(10), target: SynsetId(20),
            relation: Relation::IsA, weight: 0, provenance: 0,
        });
        let idx = AdjacencyIndex::build(&store);
        assert!(idx.outgoing(&store, SynsetId(99)).is_empty());
        assert!(idx.incoming(&store, SynsetId(99)).is_empty());
        assert_eq!(idx.outgoing_count(&store, SynsetId(99)), 0);
    }

    #[test]
    fn adjacency_index_counts_without_materializing() {
        use super::edge_store::{AdjacencyIndex, Edge, EdgeStore, Relation};
        let mut store = EdgeStore::new();
        for i in 0..500u32 {
            store.push(Edge {
                source: SynsetId(7),  // all from same hub
                target: SynsetId(i),
                relation: Relation::IsA,
                weight: 0, provenance: 0,
            });
        }
        let idx = AdjacencyIndex::build(&store);
        assert_eq!(idx.outgoing_count(&store, SynsetId(7)), 500);
        assert_eq!(idx.outgoing_count(&store, SynsetId(42)), 0);
    }

    #[test]
    fn adjacency_index_distinct_sources() {
        use super::edge_store::{AdjacencyIndex, Edge, EdgeStore, Relation};
        let mut store = EdgeStore::new();
        for src in [1u32, 1, 2, 3, 3, 3, 5] {
            store.push(Edge {
                source: SynsetId(src), target: SynsetId(100),
                relation: Relation::IsA, weight: 0, provenance: 0,
            });
        }
        let idx = AdjacencyIndex::build(&store);
        let sources: Vec<u32> = idx.distinct_sources(&store).into_iter().map(|s| s.0).collect();
        assert_eq!(sources, vec![1, 2, 3, 5]);
    }

    #[test]
    fn adjacency_index_size_is_8_bytes_per_edge() {
        use super::edge_store::{AdjacencyIndex, Edge, EdgeStore, Relation};
        let mut store = EdgeStore::new();
        for i in 0..1000u32 {
            store.push(Edge {
                source: SynsetId(i), target: SynsetId(i),
                relation: Relation::IsA, weight: 0, provenance: 0,
            });
        }
        let idx = AdjacencyIndex::build(&store);
        assert_eq!(idx.bytes_used(), 8000);  // 2 × 4 × 1000
        assert_eq!(idx.edge_count(), 1000);
    }

}
